using System;
using System.Collections.Generic;
using System.Linq;

namespace BusinessLibrary.Models.Planning
{
	public partial class IterationPlanningModel
	{

		public BurningModel Burning { get; set; }

		public void GenerateBurningData()
		{
			foreach (var day in DaysInIteration)
			{
				var burningPerDay = new BurningItemModel();
				Burning.Items.Add(burningPerDay);

				burningPerDay.ActualRemaining = CalculateActualRemaining(day, DaysInIteration.Last());

				foreach (var workingDay in WorkingDaysInIteration)
				{
					
				}
			}
		}

		public decimal CalculateActualRemaining(DateTime start, DateTime end)
		{
			return 0;
		}

		public decimal CalculateExpectedRemaining(DateTime start, DateTime end)
		{
			return 0;
		}
	}

	public class BurningModel
	{
		public BurningModel()
		{
			Items = new List<BurningItemModel>();
		}

		public List<BurningItemModel> Items { get; set; }
	}

	public class BurningItemModel
	{
		public DateTime Date { get; set; }
		public decimal ActualRemaining { get; set; }
		public decimal ExpectedRemaining { get; set; }
		/// <summary>
		/// generated by actual burning hours - efficiency of the object
		/// </summary>
		public decimal Trend { get; set; }
	}

}
